[environment]
FILENAME = "terrain.csv"
THRESHOLD = 1000
SIMPLIFICATION_CONSTANT = 4
MODE = "semnav"

[robot]
ROBOT_RADIUS = 2

[optimization]
NUM_EXPANDERS = 40
KERNEL_VARIANCE = 2
KERNEL_LENGTHSCALE = 30
BETA = 3
LIPSCHITZ = 0.003

[display]
BUFFER_SIZE = 1