[environment]
FILENAME = "terrain.csv"
THRESHOLD = 500
SIMPLIFICATION_CONSTANT = 4
MODE = "semnav"

[robot]
ROBOT_RADIUS = 2
MODE = "navigate"
STARTING_X = 40
STARTING_Y = 221
GOAL_X = 185
GOAL_Y = 360

[optimization]
NUM_EXPANDERS = 40
KERNEL_VARIANCE = 2
KERNEL_LENGTHSCALE = 30
BETA = 3
LIPSCHITZ = 0.003

[display]
BUFFER_SIZE = 1
FRAMECOUNT = 9